name: StCommonLib
main: com.stealthyone.bukkit.stcommonlib.BasePlugin
version: 2013.06.12.001
website: http://stealthyone.com/bukkit
description: Set of some useful classes that I use frequently in my plugins
author: Stealth2800
